#!/bin/sh
TO_STRING_CC=$1/to_string.cc
echo "// Automatically generated by meson at $$(date)" > ${TO_STRING_CC}
echo "// DO NOT EDIT" >> ${TO_STRING_CC}
echo >> ${TO_STRING_CC}
echo '#include "internal.hh"' >> ${TO_STRING_CC}
echo >> ${TO_STRING_CC}
echo 'DWARFPP_BEGIN_NAMESPACE' >> ${TO_STRING_CC}
echo >> ${TO_STRING_CC}
python3 libelfin/elf/enum-print.py < $1/dwarf++.hh >> ${TO_STRING_CC}
python3 libelfin/elf/enum-print.py -s _ -u --hex -x hi_user -x lo_user < $1/data.hh >> ${TO_STRING_CC}
echo 'DWARFPP_END_NAMESPACE' >> ${TO_STRING_CC}
